<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Chapter-2.-An-Array-of-Sequences" data-toc-modified-id="Chapter-2.-An-Array-of-Sequences-1">Chapter 2. An Array of Sequences</a></span><ul class="toc-item"><li><span><a href="#Built-in-sequence-types" data-toc-modified-id="Built-in-sequence-types-1.1">Built-in sequence types</a></span><ul class="toc-item"><li><span><a href="#Container-sequences" data-toc-modified-id="Container-sequences-1.1.1">Container sequences</a></span></li><li><span><a href="#Flat-sequences" data-toc-modified-id="Flat-sequences-1.1.2">Flat sequences</a></span></li><li><span><a href="#Mutable-sequences" data-toc-modified-id="Mutable-sequences-1.1.3">Mutable sequences</a></span></li><li><span><a href="#Immutable-sequences" data-toc-modified-id="Immutable-sequences-1.1.4">Immutable sequences</a></span></li><li><span><a href="#Built-in-concrete-sequence-types-subclass-the-Sequence-and-MutableSequence-abstract-base-classes-(ABCs)" data-toc-modified-id="Built-in-concrete-sequence-types-subclass-the-Sequence-and-MutableSequence-abstract-base-classes-(ABCs)-1.1.5">Built-in concrete sequence types subclass the Sequence and MutableSequence abstract base classes (ABCs)</a></span></li></ul></li><li><span><a href="#Cartesian-product-using-a-list-comprehension" data-toc-modified-id="Cartesian-product-using-a-list-comprehension-1.2">Cartesian product using a list comprehension</a></span><ul class="toc-item"><li><span><a href="#Generator-expressions-yields-items-one-by-one" data-toc-modified-id="Generator-expressions-yields-items-one-by-one-1.2.1">Generator expressions yields items one by one</a></span></li><li><span><a href="#tuple-unpacking" data-toc-modified-id="tuple-unpacking-1.2.2">tuple unpacking</a></span></li><li><span><a href="#printing-tuples-using-tuple-unpacking" data-toc-modified-id="printing-tuples-using-tuple-unpacking-1.2.3">printing tuples using tuple unpacking</a></span></li><li><span><a href="#swapping-values-using-tuple-unpacking" data-toc-modified-id="swapping-values-using-tuple-unpacking-1.2.4">swapping values using tuple unpacking</a></span></li><li><span><a href="#tuple-unpacking-using-*" data-toc-modified-id="tuple-unpacking-using-*-1.2.5">tuple unpacking using *</a></span></li></ul></li><li><span><a href="#Named-Tuples" data-toc-modified-id="Named-Tuples-1.3">Named Tuples</a></span><ul class="toc-item"><li><span><a href="#Named-tuple-attributes-and-methods" data-toc-modified-id="Named-tuple-attributes-and-methods-1.3.1">Named tuple attributes and methods</a></span></li></ul></li><li><span><a href="#Named-slicing" data-toc-modified-id="Named-slicing-1.4">Named slicing</a></span><ul class="toc-item"><li><span><a href="#Assigning-to-slices" data-toc-modified-id="Assigning-to-slices-1.4.1">Assigning to slices</a></span></li><li><span><a href="#*-operator-in-lists.-Avoid-assigning-to-duplicate-references" data-toc-modified-id="*-operator-in-lists.-Avoid-assigning-to-duplicate-references-1.4.2">* operator in lists. Avoid assigning to duplicate references</a></span></li><li><span><a href="#in-place-addition-and-multiplication-of-(mutable)-sequences-(requires-__iadd__-or-__imul__-is-implemented)" data-toc-modified-id="in-place-addition-and-multiplication-of-(mutable)-sequences-(requires-__iadd__-or-__imul__-is-implemented)-1.4.3"><code>in-place addition and multiplication of (mutable) sequences (requires __iadd__ or __imul__ is implemented)</code></a></span></li></ul></li><li><span><a href="#in-place-and-out-of-place-sorting-of-sequences" data-toc-modified-id="in-place-and-out-of-place-sorting-of-sequences-1.5">in-place and out-of-place sorting of sequences</a></span><ul class="toc-item"><li><span><a href="#out-of-place-sorting-with-sorted()" data-toc-modified-id="out-of-place-sorting-with-sorted()-1.5.1">out-of-place sorting with sorted()</a></span></li><li><span><a href="#in-place-sorting-with-list.sort()" data-toc-modified-id="in-place-sorting-with-list.sort()-1.5.2">in-place sorting with list.sort()</a></span></li></ul></li><li><span><a href="#binary-search-and-insertion" data-toc-modified-id="binary-search-and-insertion-1.6">binary search and insertion</a></span><ul class="toc-item"><li><span><a href="#Use-bisect.bisect-to-do-range-conversions" data-toc-modified-id="Use-bisect.bisect-to-do-range-conversions-1.6.1">Use bisect.bisect to do range conversions</a></span></li><li><span><a href="#Use-bisect.insort-to-insert-into-a-sorted-sequence-keeping-sequence-sorted" data-toc-modified-id="Use-bisect.insort-to-insert-into-a-sorted-sequence-keeping-sequence-sorted-1.6.2">Use bisect.insort to insert into a sorted sequence keeping sequence sorted</a></span></li></ul></li><li><span><a href="#Arrays" data-toc-modified-id="Arrays-1.7">Arrays</a></span><ul class="toc-item"><li><span><a href="#If-the-list-will-only-contain-numbers,-an-array.array-is-more-efficient-than-a-list" data-toc-modified-id="If-the-list-will-only-contain-numbers,-an-array.array-is-more-efficient-than-a-list-1.7.1">If the list will only contain numbers, an array.array is more efficient than a list</a></span></li></ul></li><li><span><a href="#Memory-Views" data-toc-modified-id="Memory-Views-1.8">Memory Views</a></span><ul class="toc-item"><li><span><a href="#The-built-in-memorview-class-is-a-shared-memory-sequence-type-that-lets-you-handle-slices-of-arrays-without-copying-bytes" data-toc-modified-id="The-built-in-memorview-class-is-a-shared-memory-sequence-type-that-lets-you-handle-slices-of-arrays-without-copying-bytes-1.8.1">The built-in memorview class is a shared-memory sequence type that lets you handle slices of arrays without copying bytes</a></span></li></ul></li><li><span><a href="#Numpy" data-toc-modified-id="Numpy-1.9">Numpy</a></span><ul class="toc-item"><li><span><a href="#NumPy-implements-multi-dimensional,-homogeneous-arrays-and-matrix-types-that-hold-not-only-numbers-but-also-user-defined-records,-and-provides-efficient-elementwise-operations." data-toc-modified-id="NumPy-implements-multi-dimensional,-homogeneous-arrays-and-matrix-types-that-hold-not-only-numbers-but-also-user-defined-records,-and-provides-efficient-elementwise-operations.-1.9.1">NumPy implements multi-dimensional, homogeneous arrays and matrix types that hold not only numbers but also user-defined records, and provides efficient elementwise operations.</a></span></li></ul></li><li><span><a href="#Deques-and-Other-Queues" data-toc-modified-id="Deques-and-Other-Queues-1.10">Deques and Other Queues</a></span><ul class="toc-item"><li><span><a href="#The-class-collections.deque-is-a-thread-safe-double-ended-queue-designed-for-fast-inserting-and-removing-from-both-ends" data-toc-modified-id="The-class-collections.deque-is-a-thread-safe-double-ended-queue-designed-for-fast-inserting-and-removing-from-both-ends-1.10.1">The class collections.deque is a thread-safe double-ended queue designed for fast inserting and removing from both ends</a></span></li><li><span><a href="#queue" data-toc-modified-id="queue-1.10.2">queue</a></span></li><li><span><a href="#multiprocessing" data-toc-modified-id="multiprocessing-1.10.3">multiprocessing</a></span></li><li><span><a href="#asyncio" data-toc-modified-id="asyncio-1.10.4">asyncio</a></span></li><li><span><a href="#heapq" data-toc-modified-id="heapq-1.10.5">heapq</a></span></li></ul></li></ul></li></ul></div>

# Chapter 2. An Array of Sequences

## Built-in sequence types

### Container sequences
can hold items of different types.
* list
* tuple
* collections.deque 

### Flat sequences
hold items of one type
* str
* bytes 
* bytearray
* memoryview
* array.array

### Mutable sequences
* list 
* bytearray 
* array.array
* collections.deque
* memoryview


### Immutable sequences
* tuple
* str
* bytes


### Built-in concrete sequence types subclass the Sequence and MutableSequence abstract base classes (ABCs)

In [44]:
import collections.abc
l = []
t = tuple()
isinstance(t, collections.abc.Sequence)

True

In [45]:
isinstance(t, collections.abc.MutableSequence)

False

## Cartesian product using a list comprehension


In [46]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

In [47]:
for color in colors:  
    for size in sizes:
        print((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [48]:
[(color, size) for color in colors      # order by color
               for size in sizes]

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [49]:
[(color, size) for size in sizes     # order by size
               for color in colors]

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

### Generator expressions yields items one by one




In [50]:
# a list with all six T-shirt variations is never produced

colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in ('%s %s' % (c, s) for c in colors for s in sizes):  
    print(tshirt)

black S
black M
black L
white S
white M
white L


### tuple unpacking

In [51]:
lax_coordinates = (33.9425, -118.408056) 
latitude, longitude = lax_coordinates 
print(latitude)
print(longitude)

33.9425
-118.408056


### printing tuples using tuple unpacking


In [53]:
print('%s/%s' % lax_coordinates) # The % formatting operator understands 
                  #  tuples and treats each item as a separate field


33.9425/-118.408056



### swapping values using tuple unpacking


In [743]:
a=1;b=2
b, a = a, b
print(a,b)

2 1


### tuple unpacking using *

In [55]:
print(divmod(20, 8))

t = (20, 8)
divmod(*t)

(2, 4)


(2, 4)

In [56]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [57]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

## Named Tuples

In [58]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')  
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))  


In [59]:
tokyo


City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [60]:
tokyo.population  

36.933

In [61]:
tokyo.coordinates

(35.689722, 139.691667)

In [64]:
tokyo[3]

(35.689722, 139.691667)

### Named tuple attributes and methods

In [65]:
City._fields

('name', 'country', 'population', 'coordinates')

In [66]:
tokyo._asdict()  

{'name': 'Tokyo',
 'country': 'JP',
 'population': 36.933,
 'coordinates': (35.689722, 139.691667)}

## Named slicing

In [69]:
invoice = """
0.....6.................................40........52...55........
1909  Pimoroni PiBrella                     $17.50    3    $52.50
1489  6mm Tactile Switch x20                 $4.95    2     $9.90
1510  Panavise Jr. - PV-201                 $28.00    1    $28.00
1601  PiTFT Mini Kit 320x240                $34.95    1    $34.95
"""
SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY =  slice(52, 55)
ITEM_TOTAL = slice(55, None)

line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])


    $17.50   Pimoroni PiBrella                 
     $4.95   6mm Tactile Switch x20            
    $28.00   Panavise Jr. - PV-201             
    $34.95   PiTFT Mini Kit 320x240            
 


### Assigning to slices

In [72]:
l = list(range(10))
l[2:4] = [20, 30]
l

[0, 1, 20, 30, 4, 5, 6, 7, 8, 9]

In [73]:
del  l[5:7]
l

[0, 1, 20, 30, 4, 7, 8, 9]

In [74]:
l[3::2] = [33,77,99]
l

[0, 1, 20, 33, 4, 77, 8, 99]

In [75]:
l[2:5] = [999]
l

[0, 1, 999, 77, 8, 99]

### * operator in lists. Avoid assigning to duplicate references

In [78]:
weird_board = [['_'] * 3] * 3
weird_board[1][0] = 'X' 
weird_board

[['X', '_', '_'], ['X', '_', '_'], ['X', '_', '_']]

In [79]:
ok_board = [['_'] * 3 for _ in range(3)] 
ok_board[1][0] = 'X'
ok_board

[['_', '_', '_'], ['X', '_', '_'], ['_', '_', '_']]

### `in-place addition and multiplication of (mutable) sequences (requires __iadd__ or __imul__ is implemented)`

In [89]:
l = [1, 2, 3]
id(l)

140335947458048

In [90]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [91]:
id(l)

140335947458048

immutable sequences make copies with inplace operators (no inplace operation)

In [95]:
t = (1, 2, 3)
id(t)

140335947294208

In [97]:
t *= 2
t

(1, 2, 3, 1, 2, 3)

In [98]:
id(t)

140335943634752

## in-place and out-of-place sorting of sequences

### out-of-place sorting with sorted()

In [99]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [100]:
fruits

['grape', 'raspberry', 'apple', 'banana']

### in-place sorting with list.sort()


In [101]:
list.sort(fruits)
fruits

['apple', 'banana', 'grape', 'raspberry']

## binary search and insertion

In [102]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    print('DEMO:', bisect_fn.__name__)   
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)   
        offset = position * '  |'   
        print(ROW_FMT.format(needle, position, offset))   


In [103]:
bisect_fn = bisect.bisect
demo(bisect_fn)

DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [104]:
bisect_fn = bisect.bisect_left
demo(bisect_fn)

DEMO: bisect_left
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 12      |  |  |  |  |  |  |  |  |  |  |  |29
23 @  9      |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  4      |  |  |  |8 
 5 @  2      |  |5 
 2 @  1      |2 
 1 @  0    1 
 0 @  0    0 


### Use bisect.bisect to do range conversions

In [107]:
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

### Use bisect.insort to insert into a sorted sequence keeping sequence sorted

In [113]:
import bisect
import random

SIZE = 7

# random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

 5 -> [5]
11 -> [5, 11]
10 -> [5, 10, 11]
11 -> [5, 10, 11, 11]
12 -> [5, 10, 11, 11, 12]
 6 -> [5, 6, 10, 11, 11, 12]
 9 -> [5, 6, 9, 10, 11, 11, 12]


## Arrays

### If the list will only contain numbers, an array.array is more efficient than a list

array.tofile 60x faster reads than from text file YMMV

In [214]:
import time

def clock(func):
    def clocked(*args):  
        t0 = time.perf_counter()
        result = func(*args)  
        elapsed = time.perf_counter() - t0
        name = func.__name__
        arg_str = ', '.join(repr(arg) for arg in args)
        print('[%0.8fs] %s(%s) -> %r' % (elapsed, name, arg_str, result))
        return result
    return clocked  

In [215]:
from random import random
from array import array

floats = array('d', (random() for i in range(10**7))) 

fp = open('floats.txt', 'w')
fp.write(str(floats)) 
fp.close()

fp = open('floats.bin', 'wb')
floats.tofile(fp) 
fp.close()

floats1 = []
floats2 = array('d')
fp1 = open('floats.txt', 'r')
fp2 = open('floats.bin', 'rb')


In [216]:
@clock
def read_txt():
    floats1 = fp1.read()
read_txt()

[0.27750215s] read_txt() -> None


In [217]:
@clock
def read_bin():
    floats2.fromfile(fp2, 10**7)  
read_bin()

[0.03754797s] read_bin() -> None


In [220]:
floats == floats2

True

In [221]:
fp1.close()
fp2.close()

In [222]:
0.27750215/0.03754797

7.390603273625711

## Memory Views

### The built-in memorview class is a shared-memory sequence type that lets you handle slices of arrays without copying bytes

In [188]:
numbers = array('h', [-2, -1, 0, 1, 2]) 
memv = memoryview(numbers)  # memoryview from array of 
                            # 5 short signed integers (typecode 'h')

len(memv)

5

In [189]:
memv[0]  

-2

In [190]:
memv_oct = memv.cast('B') # cast the elements of memv to typecode 'B' (unsigned char).
memv_oct.tolist()  

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [191]:
memv_oct[5] = 4  # Assign value 4 to byte offset 5
numbers # Note change to numbers: a 4 in the most significant byte of a 2-byte unsigned integer is 1024.

array('h', [-2, -1, 1024, 1, 2])

## Numpy

### NumPy implements multi-dimensional, homogeneous arrays and matrix types that hold not only numbers but also user-defined records, and provides efficient elementwise operations.

In [192]:
import numpy  
a = numpy.arange(12)  
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [193]:
type(a)

numpy.ndarray

In [194]:
a.shape  

(12,)

In [195]:
a.shape = 3, 4  
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [196]:
a[2]  

array([ 8,  9, 10, 11])

In [197]:
a[2, 1]  

9

In [198]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [200]:
a[:, 1]  

array([1, 5, 9])

## Deques and Other Queues

### The class collections.deque is a thread-safe double-ended queue designed for fast inserting and removing from both ends

In [201]:
from collections import deque
dq = deque(range(10), maxlen=10)  
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [202]:
dq.rotate(3)  
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [203]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [204]:
dq.appendleft(-1)  # appendleft discards items from the other end
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
# Adding three items to the right pushes out the leftmost 3
dq.extend([11, 22, 33]) 
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [206]:
dq.extendleft([10, 20, 30, 40])  
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])

### queue

 provides the synchronized (i.e., thread-safe) classes Queue, LifoQueue, and PriorityQueue. These are used for safe communication between threads. All three classes can be bounded by providing a maxsize argument greater than 0 to the constructor. However, they don’t discard items to make room as deque does. Instead, when the queue is full the insertion of a new item blocks

### multiprocessing
Implements its own bounded Queue, very similar to queue.Queue but designed for interprocess communication. A specialized multiprocessing.JoinableQueue is also available for easier task management.


### asyncio
Newly added to Python 3.4, asyncio provides Queue, LifoQueue, PriorityQueue, and JoinableQueue with APIs inspired by the classes contained in the queue and multiprocessing modules, but adapted for managing tasks in asynchronous programming.


### heapq
In contrast to the previous three modules, heapq does not implement a queue class, but provides functions like heappush and heappop that let you use a mutable sequence as a heap queue or priority queue.